
name: Deploy to GCP DEV VM

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GCP_VM_SSH_PRIVATE_KEY}}

      - name: Sync files to remote server using rsync
        run: |
          rsync -avz --delete --delete --exclude='.git/' --exclude='.github/' --exclude='node_modules/' --include='.*' --include='*' --prune-empty-dirs -e "ssh -vvv -o StrictHostKeyChecking=no" ./ ${{ secrets.GCP_VM_USERNAME }}@${{ secrets.GCP_VM_IP }}:/home/maruthiwork0009/task2
        env:
          GCP_VM_USERNAME: ${{ secrets.GCP_VM_USERNAME}}
          GCP_VM_IP: ${{ secrets.GCP_VM_IP }}

      - name: SSH into the server and deploy with Docker Compose
        env:
          GCP_VM_USERNAME: ${{ secrets.GCP_VM_USERNAME }}
          GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{secrets.GCP_VM_USERNAME}}@${{secrets.GCP_VM_IP}} << 'EOF'
            set -e
            cd /home/maruthiwork0009/task2/
           sudo docker system prune -af
           sudo docker build -t svelte .
           sudo docker compose up -d
          EOF
